/*
 * DebugFrame.java
 *
 * Created on 05 January 2006, 16:10
 */

package lsat.gui;


import lsat.log.*;
/**
 *
 * @author  stone
 */
public class DebugFrame extends javax.swing.JInternalFrame{
    
    /** Creates new form DebugFrame */
    public DebugFrame() {
        initComponents();
        Log theLog = LogFactory.getLog();
        theLog.setOutputTextArea(this.jTextArea1);
        
        setLocation(0,0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Debug");
        setPreferredSize(new java.awt.Dimension(300, 500));
        setVisible(true);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
