/*
 * DocumentViewerFrame.java
 *
 * Created on 20 December 2005, 11:09
 */

package lsat.gui;

import java.util.*;
import lsat.structures.*;
import javax.swing.*;
import java.beans.*;
/**
 *
 * @author  stone
 */
public class DocumentViewerFrame extends javax.swing.JInternalFrame
{
    
    /** Creates new form DocumentViewerFrame */
    public DocumentViewerFrame(String documentName, String content) 
    {
        initComponents();
        this.setTitle(documentName);
        contentArea.setText(content);
        contentArea.setCaretPosition(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane = new javax.swing.JScrollPane();
        contentArea = new javax.swing.JTextArea();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        contentArea.setEditable(false);
        contentArea.setLineWrap(true);
        contentArea.setWrapStyleWord(true);
        jScrollPane.setViewportView(contentArea);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contentArea;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
