/*
 * DocumentFrame.java
 *
 * Created on 20 December 2005, 11:09
 */

package lsat.gui;

import java.util.*;
import lsat.structures.*;
import javax.swing.*;
import java.awt.*;
import java.beans.PropertyVetoException;

/**
 *
 * @author  stone
 */
public class DocumentFrame extends javax.swing.JInternalFrame {
    
    private JDesktopPane parent;
    private DocumentFrameTableModel theModel;
    private ArrayList<Document> documentCollection;
    
    /** Creates new form DocumentFrame */
    public DocumentFrame(DocumentFrameTableModel theModel, JDesktopPane parent, ArrayList<Document> documentCollection) {
        initComponents();
        this.parent = parent;
        this.documentCollection = documentCollection;
        this.theModel = theModel;
        jTable.setModel(this.theModel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Documents");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setVisible(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });

        jScrollPane.setViewportView(jTable);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated

    }//GEN-LAST:event_formInternalFrameDeactivated

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    }//GEN-LAST:event_formInternalFrameActivated

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if(evt.getClickCount() == 2)
        {
            int selectedDocumentIndex = jTable.getSelectedRow();
            
            if(selectedDocumentIndex >= 0)
            {
                String name = this.theModel.getValueAt(selectedDocumentIndex, 2).toString();
                String content = documentCollection.get(selectedDocumentIndex).getContent();
                DocumentViewerFrame f = new DocumentViewerFrame(name, content);
                f.setSize(400,400);
                Point newLocation = new Point(this.getLocation());
                newLocation.translate(25,25);
                f.setLocation(newLocation);
                parent.add(f);
                
                f.setVisible(true);                
            }
        }
    }//GEN-LAST:event_jTableMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
    
}
